/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/bootstrap": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Bootstrap */
    get: operations["bootstrap_api_bootstrap_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Runs */
    get: operations["runs_api_runs_get"];
    put?: never;
    /** Start */
    post: operations["start_api_runs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Run */
    get: operations["run_api_runs__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/steps": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Steps */
    get: operations["steps_api_runs__run_id__steps_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Events */
    get: operations["events_api_runs__run_id__events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/tree": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Tree */
    get: operations["tree_api_runs__run_id__tree_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/file": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** File */
    get: operations["file_api_runs__run_id__file_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/media": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Media */
    get: operations["media_api_runs__run_id__media_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/table": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Table */
    get: operations["table_api_runs__run_id__table_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/steps/{step_id}/source": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Source */
    get: operations["source_api_steps__step_id__source_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/inspect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Inspect */
    post: operations["inspect_api_inspect_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel */
    post: operations["cancel_api_runs__run_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/reveal": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Open Folder */
    post: operations["open_folder_api_runs__run_id__reveal_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ArtifactView */
    ArtifactView: {
      /** Rel */
      rel: string;
      /** Size */
      size: number;
      /** Quality Label */
      quality_label: string;
    };
    /** Bootstrap */
    Bootstrap: {
      /** Token */
      token: string;
      /** Python */
      python: string;
      /** Script */
      script: string;
      /** Gmt */
      gmt: string;
      /** Group Note */
      group_note: string;
      /** Engine Name */
      engine_name: string;
      /** Engine Version */
      engine_version: string;
      /** Engine Git */
      engine_git: string;
      /** Environment Ok */
      environment_ok: boolean;
    };
    /** ColumnView */
    ColumnView: {
      /** Name */
      name: string;
      /** Values */
      values: string[];
    };
    /** FilePreview */
    FilePreview: {
      /** Rel */
      rel: string;
      /** Text */
      text: string;
      /** Truncated */
      truncated: boolean;
      /** Note */
      note: string;
      /** Size */
      size: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ImageView */
    ImageView: {
      /** Rel */
      rel: string;
      /** Step Id */
      step_id: string;
      /** Step Name */
      step_name: string;
      /** Passed */
      passed: boolean;
      /** Label */
      label: string;
      /** Reasons */
      reasons: components["schemas"]["ReasonView"][];
    };
    /** InspectView */
    InspectView: {
      /** Columns */
      columns: components["schemas"]["ColumnView"][];
      /** Note */
      note: string;
      /** Group Note */
      group_note: string;
      /** Input Path */
      input_path: string;
      /** Gene */
      gene: string;
      /** Out */
      out: string;
      /** Local Gmt */
      local_gmt: string;
    };
    /** LogView */
    LogView: {
      /** Name */
      name: string;
      /** Text */
      text: string;
    };
    /** ParameterRow */
    ParameterRow: {
      /** Name */
      name: string;
      /** Value */
      value: string;
      /** Source */
      source: string;
      /** Source Label */
      source_label: string;
    };
    /**
     * QuicklookForm
     * @description Fields the page may submit. The engine program is not one of them.
     */
    QuicklookForm: {
      /** Input Path */
      input_path: string;
      /** Gene */
      gene: string;
      /** Out */
      out: string;
      /**
       * Group
       * @default
       */
      group: string;
      /**
       * Case Label
       * @default
       */
      case_label: string;
      /**
       * Control Label
       * @default
       */
      control_label: string;
      /**
       * Batch Column
       * @default
       */
      batch_column: string;
      /**
       * Local Gmt
       * @default
       */
      local_gmt: string;
    };
    /** ReasonView */
    ReasonView: {
      /** Code */
      code: string;
      /** Text */
      text: string;
      /** Suggestion */
      suggestion: string;
    };
    /** RevealResult */
    RevealResult: {
      /** Status */
      status: string;
    };
    /** RunListItem */
    RunListItem: {
      /** Run Id */
      run_id: string;
      /** Task Id */
      task_id: string;
      /** Status */
      status: string;
      /** Status Label */
      status_label: string;
      /** Heading */
      heading: string;
      /** Returncode */
      returncode: number | null;
      /** Enrichment */
      enrichment: string;
      /** Stopped After */
      stopped_after: string;
    };
    /** RunView */
    RunView: {
      /** Run Id */
      run_id: string;
      /** Task Id */
      task_id: string;
      /** Status */
      status: string;
      /** Status Label */
      status_label: string;
      /** Heading */
      heading: string;
      /** Lede */
      lede: string;
      /** Can Cancel */
      can_cancel: boolean;
      /** Returncode */
      returncode: number | null;
      /** Enrichment */
      enrichment: string;
      /** Enrichment Label */
      enrichment_label: string;
      /** Stopped After */
      stopped_after: string;
      /** Output Root */
      output_root: string;
      /** Engine Name */
      engine_name: string;
      /** Engine Version */
      engine_version: string;
      /** Engine Git */
      engine_git: string;
      /** Command */
      command: string[];
      /** Command Line */
      command_line: string;
      /** Config Text */
      config_text: string;
      /** Parameters */
      parameters: components["schemas"]["ParameterRow"][];
      /** Logs */
      logs: components["schemas"]["LogView"][];
      /** Pipeline Outcome */
      pipeline_outcome: string;
      /** Pipeline Label */
      pipeline_label: string;
      /** Figure Status */
      figure_status: string;
      /** Figure Label */
      figure_label: string;
      /** Images */
      images: components["schemas"]["ImageView"][];
    };
    /** SourceView */
    SourceView: {
      /** Step Id */
      step_id: string;
      /** Name */
      name: string;
      /** Script Name */
      script_name: string;
      /** Sha256 */
      sha256: string;
      /** Engine Version */
      engine_version: string;
      /** Engine Git */
      engine_git: string;
      /** Source */
      source: string;
    };
    /** Started */
    Started: {
      /** Run Id */
      run_id: string;
    };
    /** StepView */
    StepView: {
      /** Step Id */
      step_id: string;
      /** Name */
      name: string;
      /** Status */
      status: string;
      /** Status Label */
      status_label: string;
      /** Script Name */
      script_name: string;
      /** Artifacts */
      artifacts: components["schemas"]["ArtifactView"][];
    };
    /** TablePage */
    TablePage: {
      /** Rel */
      rel: string;
      /** Columns */
      columns: string[];
      /** Rows */
      rows: string[][];
      /** Offset */
      offset: number;
      /** Limit */
      limit: number;
    };
    /** TreeEntry */
    TreeEntry: {
      /** Rel */
      rel: string;
      /** Kind */
      kind: string;
      /** Size */
      size: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  bootstrap_api_bootstrap_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Bootstrap"];
        };
      };
    };
  };
  runs_api_runs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunListItem"][];
        };
      };
    };
  };
  start_api_runs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["QuicklookForm"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Started"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  run_api_runs__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  steps_api_runs__run_id__steps_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StepView"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  events_api_runs__run_id__events_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  tree_api_runs__run_id__tree_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TreeEntry"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  file_api_runs__run_id__file_get: {
    parameters: {
      query: {
        rel: string;
      };
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FilePreview"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  media_api_runs__run_id__media_get: {
    parameters: {
      query: {
        rel: string;
      };
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  table_api_runs__run_id__table_get: {
    parameters: {
      query: {
        rel: string;
        offset?: number;
        limit?: number;
      };
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TablePage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  source_api_steps__step_id__source_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        step_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  inspect_api_inspect_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["QuicklookForm"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InspectView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_api_runs__run_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  open_folder_api_runs__run_id__reveal_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RevealResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
