/** Visible labels that are not sent by the API. Status and reason text stay on the server. */
export const chrome = {
  quicklook: "速览",
  formal: "正式分析",
  formalNote: "正式分析还没有接到这个界面。",
  cancel: "取消",
  environmentOk: "环境✓",
  environmentBad: "环境不可用",
  steps: "步骤",
  files: "文件",
  images: "图片",
  assistant: "助手",
  assistantNote: "未接入",
  log: "日志",
  code: "代码",
  parameters: "参数",
  artifacts: "产物",
  engine: "引擎",
  input: "输入",
  quality: "图质量",
  enrichment: "富集",
  copyCommand: "复制为命令",
  copied: "已复制",
  reveal: "在资源管理器中打开",
  noRun: "还没有运行",
  noLog: "这次还没有日志。",
  noImage: "这次还没有图。",
  compare: "并排对比",
  download: "下载原图",
  close: "关闭",
  inspect: "检查输入",
  start: "开始速览",
  gene: "目标基因",
  inputPath: "数据路径",
  output: "输出目录",
  gmt: "本地 GMT",
  gmtNote:
    "软件没有附带基因集。留空就停在聚类，不做差异分析，也不做富集。要做这两步，填一个你有权使用的本地 GMT 文件。",
  group: "分组列",
  caseLabel: "case",
  controlLabel: "control",
  batch: "批次列",
  noneGroup: "不分组",
  noneValue: "不指定",
  noneBatch: "不指定批次",
  argv: "实际命令",
  config: "解析后的配置",
  script: "步骤脚本",
  project: "运行",
  newRun: "新的速览",
  demo: "运行演示",
  environment: "环境",
  back: "返回步骤",
  searchGene: "搜索基因",
  searchPlaceholder: "过滤基因符号",
  preview: "预览",
  basicInputs: "基础输入参数",
  groupSection: "观测矩阵探测与分组",
  runtime: "执行环境",
  inputPlaceholder: "h5ad 文件，或 10x mtx 目录",
  genePlaceholder: "例如 IFITM3",
  outputPlaceholder: "空目录，或还不存在的目录",
  gmtPlaceholder: "本地基因集文件，可留空",
  currentStep: "当前步骤",
  parameter: "参数",
  value: "值",
  source: "来源",
  otherFigures: "其他",
  suggestion: "建议：",
  cannotPreview: "这个文件不能在页面里打开。",
  kindImage: "图片",
  kindTable: "表格",
  kindText: "文本",
  kindOther: "其他",
  methodsHeading: "方法",
  bundle: "下载复现包",
  compareRuns: "对比",
  leftRun: "左侧运行",
  rightRun: "右侧运行",
  cells: "细胞数",
  clusters: "cluster 数",
  notify: "运行结束时通知我",
  notifyOn: "结束时会通知",
} as const;

export function rowCount(total: number): string {
  return `共 ${total} 行`;
}
